/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#define INI_Char_TYPE_Ops() {} 

#define ASSIGN_ANY_STR(r) { r[0] = (char)'\0' ;}

#define LEN_STR(n,s) { *(n) = strlen((char *)s) ;}

#define VAL_ITH_CHAR(c,s,i) { *(c) = ((char *)s)[i-1] ;}

#define CHAR_TO_NAT(i,c) { *(i) = (long)c ;}

#define CMP_STR(b,r,s) { *(b) = ( strcmp((char *)r,(char *)s) == 0 ) ;}

#define SMR_STR(b,r,s) { *(b) = ( strcmp((char *)r,(char *)s) < 0 ) ;}

void CPY_STR ();
void CNC_STR ();
