/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_UiArrO1.h"

#include "Rename_O1_UiArr.h"
#include "Rename_N1_Uns.h"

#include "Bool_TYPE.h"
#include "PASP_TYPE.h"

void
INI_Rename_UiArrO1(void)
{
  INI_Rename_O1_UiArr();
  INI_Rename_N1_Uns();
  {
    int ii;
    ii = 0;
    while ( ii < Rename_UiArrO1P1 ) {
      UINC(&ii,ii);
      Rename_O1_STO(ii,Rename_UiArrO1P2);
    };
    Rename_N1_STO(1);
  }
}

void
Rename_UiAO1_RST(void)
{
  Rename_N1_STO(1);
}

void
Rename_UiAO1_VAL(int *_vv,int _ii)
{
  Rename_O1_VAL(_vv,_ii);
}

void
Rename_UiAO1_NXT(int *_nn)
{
  Rename_N1_VAL(_nn);
}

void
Rename_UiAO1_STO(int _ii,int _vv)
{
  int jj;
  Rename_O1_STO(_ii,_vv);
  if ( _ii < Rename_UiArrO1P1 ) {
    UINC(&jj,_ii);
    Rename_N1_STO(jj);
  }
  else {
    Rename_N1_STO(1);
  }
}

void
Rename_UiAO1_STO_NXT(int _vv)
{
  int ii;
  Rename_N1_VAL(&ii);
  Rename_O1_STO(ii,_vv);
  if ( ii < Rename_UiArrO1P1 ) {
    Rename_N1_INC();
  }
  else {
    Rename_N1_STO(1);
  }
}

void
Rename_UiAO1_FILL(int _vv)
{
  int ii;
  ii = 0;
  while ( ii < Rename_UiArrO1P1 ) {
    UINC(&ii,ii);
    Rename_O1_STO(ii,_vv);
  };
  Rename_N1_STO(1);
}

