/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_BiRcdP1;
extern int Rename_BiRcdP2;
extern int Rename_BiRcdP3;

extern int Rename_BiRcd_ARR_BiArrP1;
extern int Rename_BiRcd_ARR_BiArrP2;
extern int Rename_BiRcd_ARR_BiArrP3;

extern int Rename_BiRcd_ARR[];

extern int Rename_BiRcd_HEAP_ARR_BiArrP1;
extern int Rename_BiRcd_HEAP_ARR_BiArrP2;
extern int Rename_BiRcd_HEAP_ARR_BiArrP3;

extern int Rename_BiRcd_HEAP_ARR[];

extern int Rename_BiRcd_TOT;

void INI_Rename_BiRcd();
void Rename_BiRcd_RST();
void Rename_BiRcd_IDX();
void Rename_BiRcd_FULL();
void Rename_BiRcd_CRE();
void Rename_BiRcd_KILL();
void Rename_BiRcd_VLD();
void Rename_BiRcd_STO();
void Rename_BiRcd_VAL();
