/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_Segment_io.h"

void
#ifdef _BT_ANSIC
Rename_PUT_SEG( int vv )
#else
Rename_PUT_SEG( vv )
int vv;
#endif
{
	int i;
	int *p;
	p = (int *)vv;
	i = 0;
	while(i < Rename_Segment_ioP1){
		printf("\n%d: %d",i,p[i]); 
		i = i+1;
	};
}


void
#ifdef _BT_ANSIC
Rename_GET_SEG( int *rr )
#else
Rename_GET_SEG( rr )
int *rr;
#endif
{
	int i;
	i = 0;
	printf("\n");
	while(i < Rename_Segment_ioP1){
		printf("%d: ",i);
		Rename_GET_RAW(&rr[i],214748364);
		i = i+1;
	};
}


void
#ifdef _BT_ANSIC
Rename_GET_PROMPT_SEG( int *rr, int *ss )
#else
Rename_GET_PROMPT_SEG( rr, ss )
int *rr, *ss;
#endif
{
	int i;
	printf(ss);
	i = 0;
	printf("\n");
	while(i < Rename_Segment_ioP1){
		printf("%d: ",i);
		Rename_GET_RAW(&rr[i],214748364);
		i = i+1;
	};
}



#define mess_tok  while( c!='\n' ){ \
                    c = getchar(); \
                  }; \
                  printf("    Not a token (0..%d) - Re-Input: ",d)

#define init_tok  n = 0; \
                  while( (c<'0') || (c>'9') ){ \
                    mess_tok; \
                    c = getchar(); \
                  }


void
#ifdef _BT_ANSIC
Rename_GET_RAW( int *r, int d )
#else
Rename_GET_RAW( r, d )
int *r, d;
#endif
{
	register int c,m,k,l,n ;
	{
		k = d/10;
		l = d-10*(d/10);
		c = getchar();
		init_tok;
		while( (c>='0') && (c<='9') ){
			m = c-'0';
			if( n<k ){
				n = 10*n+m;
				c = getchar();
			} else if( n == k ){
				if( m<=l ){
					n = 10*n+m;
					c = getchar();
				} else{
					mess_tok;
					c = getchar();
					init_tok;
				};
			} else{
				mess_tok;
				c = getchar();
				init_tok;
			};
		};
		while( c!='\n' ){
			c = getchar();
		};
		*r = n;
	};
}


void
#ifdef _BT_ANSIC
Rename_GET_PROMPT_RAW( int *r, char *s, int d )
#else
Rename_GET_PROMPT_RAW( r, s, d )
int *r, d;
char *s;
#endif
{
	register int c,m,k,l,n ;
	{
		k = d/10;
		l = d-10*(d/10);
		printf(s);
		c = getchar();
		init_tok;
		while( (c>='0') && (c<='9') ){
			m = c-'0';
			if( n<k ){
				n = 10*n+m;
				c = getchar();
			} else if( n == k ){
				if( m<=l ){
					n = 10*n+m;
					c = getchar();
				} else{
					mess_tok;
					c = getchar();
					init_tok;
				};
			} else{
				mess_tok;
				c = getchar();
				init_tok;
			};
		};
		while( c!='\n' ){
			c = getchar();
		};
		*r = n;
	};
}

