/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern char * Rename_set_objP1 [];
extern int Rename_set_objP2;
extern int Rename_set_objP3;
extern int Rename_tot_set_obj;

extern int Rename_adr_set_obj[];
extern int Rename_ssiz_adr_set_obj;

extern int Rename_len_set_obj[];
extern int Rename_ssiz_len_set_obj;

extern int Rename_old_set_obj[];
extern int Rename_ssiz_old_set_obj;

extern int Rename_array_set_obj[];

#define Rename_STS_SET_OBJ(mm,nn,pp,qq) \
{ \
  *(mm) = (Rename_set_objP3) - Rename_tot_set_obj; \
  *(nn) = (Rename_set_objP3); \
  *(pp) = (Rename_ssiz_len_set_obj-1-Rename_ssiz_old_set_obj); \
  *(qq) = (Rename_set_objP2); \
}

#define Rename_MEM_FUL_SET_OBJ(bb) \
{*(bb) = ((Rename_tot_set_obj == 0)!=0);}

#define Rename_OBJ_FUL_SET_OBJ(bb)     \
{*(bb) = ((Rename_ssiz_len_set_obj-1-Rename_ssiz_old_set_obj == Rename_set_objP2)!=0);}

#define Rename_ANY_SET_OBJ(pp) \
{*(pp) = 1; }

#define Rename_FRE_MEM_SET_OBJ(nn) \
{*(nn) =  Rename_tot_set_obj;}

#define Rename_FRE_OBJ_SET_OBJ(nn)     \
{*(nn) = (Rename_set_objP2-Rename_ssiz_len_set_obj+1+Rename_ssiz_old_set_obj);}

#define Rename_XST_ORD_SET_OBJ(bb,pp,ii)   \
{*(bb) = ((ii>0) && (ii <= Rename_len_set_obj[pp]))!=0;}

#define Rename_EMP_SET_OBJ(bb,pp)  \
{*(bb) = ((Rename_len_set_obj[pp] == 0)!=0);}

#define Rename_CLR_SET_OBJ(ss) \
{Rename_tot_set_obj = Rename_tot_set_obj+Rename_len_set_obj[ss];Rename_len_set_obj[ss] = 0;}

#define Rename_KIL_SET_OBJ(pp) \
{Rename_CLR_SET_OBJ(pp); \
 Rename_ssiz_old_set_obj=Rename_ssiz_old_set_obj+1; \
 Rename_old_set_obj[Rename_ssiz_old_set_obj]=pp;}

#define Rename_STO_SET_OBJ(ss,ii,vv)  \
{Rename_array_set_obj[ii+Rename_adr_set_obj[ss]] = vv;}

#define Rename_VAL_SET_OBJ(vv,ss,ii)  \
{*(vv) = Rename_array_set_obj[ii+Rename_adr_set_obj[ss]];}

#define Rename_POP_SET_OBJ(pp)        \
{Rename_len_set_obj[pp] = Rename_len_set_obj[pp]-1; Rename_tot_set_obj = Rename_tot_set_obj+1;}

#define Rename_LEN_SET_OBJ(nn,pp)     \
{*(nn) = Rename_len_set_obj[pp];}

#define Rename_CRD_SET_OBJ(nn,pp)     \
{Rename_LEN_SET_OBJ(nn,pp);}

void INI_Rename_set_obj();
void Rename_XST_SET_OBJ();
void Rename_SAV_SET_OBJ();
void Rename_SAVN_SET_OBJ();
void Rename_RST_SET_OBJ();
void Rename_RSTN_SET_OBJ();
void Rename_CRE_SET_OBJ();
void Rename_MBR_SET_OBJ();
void Rename_ENT_SET_OBJ();
void Rename_RMV_SET_OBJ();
