/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_BiBArr.h"

#include "Rename_B_BiArr.h"
#include "Rename_N_Byt.h"

#include "Byt_TYPE.h"
#include "Bool_TYPE.h"

void
INI_Rename_BiBArr(void)
{
  int idx = Rename_BiBArrP1;
  INI_Rename_B_BiArr();
  INI_Rename_N_Byt();
  Rename_N_STO(Rename_BiBArrP2);
  while (idx <= Rename_BiBArrP2) {
    Rename_B_STO(idx++,Rename_BiBArrP3);
  }
}

void
Rename_BiBA_IDX(int *_bb,int _idx)
{
  if ( Rename_BiBArrP1 <= _idx && _idx <= Rename_BiBArrP2 ) {
    *_bb = TRUE;
  }
  else {
    *_bb = FALSE;
  }
}

void
Rename_BiBA_VAL(int *_vv,int _idx)
{
  Rename_B_VAL(_vv,_idx);
}

void
Rename_BiBA_STO(int _idx,int _vv)
{
  int nx;
  Rename_B_STO(_idx,_vv);
  BINC(&nx,_idx);
  if ( nx < Rename_BiBArrP2 ) {
    Rename_N_INC();
  }
  else {
    Rename_N_STO(Rename_BiBArrP1);
  }
}

void
Rename_BiBA_EQ(int *_bb,int _idx,int _vv)
{
  Rename_B_EQ(_bb,_idx,_vv);
}

void
Rename_BiBA_IEQ(int *_bb,int _idx,int _idx2)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  Rename_B_EQ(_bb,_idx2,yy);
}

void
Rename_BiBA_NE(int *_bb,int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BNE(_bb,yy,_vv);
}

void
Rename_BiBA_INE(int *_bb,int _idx,int _idx2)
{
  int yy,vv;
  Rename_B_VAL(&yy,_idx);
  Rename_B_VAL(&vv,_idx2);
  BNE(_bb,yy,vv);
}

void
Rename_BiBA_GT(int *_bb,int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BGT(_bb,yy,_vv);
}

void
Rename_BiBA_IGT(int *_bb,int _idx,int _idx2)
{
  int yy,vv;
  Rename_B_VAL(&yy,_idx);
  Rename_B_VAL(&vv,_idx2);
  BGT(_bb,yy,vv);
}

void
Rename_BiBA_GE(int *_bb,int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BGE(_bb,yy,_vv);
}

void
Rename_BiBA_IGE(int *_bb,int _idx,int _idx2)
{
  int yy,vv;
  Rename_B_VAL(&yy,_idx);
  Rename_B_VAL(&vv,_idx2);
  BGE(_bb,yy,vv);
}

void
Rename_BiBA_LT(int *_bb,int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BLT(_bb,yy,_vv);
}

void
Rename_BiBA_ILT(int *_bb,int _idx,int _idx2)
{
  int yy,vv;
  Rename_B_VAL(&yy,_idx);
  Rename_B_VAL(&vv,_idx2);
  BLT(_bb,yy,vv);
}

void
Rename_BiBA_LE(int *_bb,int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BLE(_bb,yy,_vv);
}

void
Rename_BiBA_ILE(int *_bb,int _idx,int _idx2)
{
  int yy,vv;
  Rename_B_VAL(&yy,_idx);
  Rename_B_VAL(&vv,_idx2);
  BLE(_bb,yy,vv);
}

void
Rename_BiBA_ADD(int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BADD(&yy,yy,_vv);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_IADD(int _idx,int _idx2)
{
  int yy,vv;
  Rename_B_VAL(&yy,_idx);
  Rename_B_VAL(&vv,_idx2);
  BADD(&yy,yy,vv);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_SUB(int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BSUB(&yy,yy,_vv);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_ISUB(int _idx,int _idx2)
{
  int yy,vv;
  Rename_B_VAL(&yy,_idx);
  Rename_B_VAL(&vv,_idx2);
  BSUB(&yy,yy,vv);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_INC(int _idx)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BINC(&yy,yy);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_DEC(int _idx)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BDEC(&yy,yy);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_MUL(int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BMUL(&yy,yy,_vv);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_DIV(int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BDIV(&yy,yy,_vv);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_REM(int _idx,int _vv)
{
  int yy;
  Rename_B_VAL(&yy,_idx);
  BMOD(&yy,yy,_vv);
  Rename_B_STO(_idx,yy);
}

void
Rename_BiBA_STO_NXT(int _vv)
{
  int nx;
  Rename_N_VAL(&nx);
  Rename_B_STO(nx,_vv);
  if ( nx < Rename_BiBArrP2 ) {
    Rename_N_INC();
  }
  else {
    Rename_N_STO(Rename_BiBArrP1);
  }
}

void
Rename_BiBA_FILL(int _vv)
{
  int idx;
  idx = Rename_BiBArrP1;
  while ( idx <= Rename_BiBArrP2 ) {
    Rename_B_STO(idx,_vv);
    BINC(&idx,idx);
  };
  Rename_N_STO(Rename_BiBArrP1);
}

void
Rename_BiBA_NXT(int *_nn)
{
  Rename_N_VAL(_nn);
}

