/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_Timer.h"
#include "Bool_TYPE.h"
#include "Scalar_TYPE.h"

#define __inc_month \
  { \
    _dd = 1; \
    _mm++; \
    if ( _mm == 13 ) { _mm = 1; _yy++; } \
  }

void
Rename_IncYearMonthDay( int * _inc_ymd, int _ymd, int _days )
{
  int _loop_n    = _days;
  int _dd        = _ymd-100*(_ymd/100);
  int _mm        = (_ymd/100)-100*(_ymd/10000);
  int _yy        = _ymd/10000;
  while ( _loop_n ) {
    switch ( _dd ) {
    case 31:
      __inc_month;
      break;
    case 30:
      switch ( _mm ) {
      case  9:
      case  4:
      case  6:
      case 11:
        __inc_month;
        break;
      default :
        _dd++;
        break;
      }
      break;
    case 29:
      switch ( _mm ) {
      case  2:
        __inc_month;
        break;
      default :
        _dd++;
        break;
      }
      break;
    case 28:
      switch ( _mm ) {
      case  2:
        if ( _yy == _yy-4*(_yy/4) ) _dd++;
        else  __inc_month;
        break;
      default :
        _dd++;
        break;
      }
      break;
    default:
      _dd++;
      break;
    }
    _loop_n--;
  }
  * _inc_ymd = (_yy*10000)+(_mm*100)+_dd;
}
