/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename;

/************** OPERATIONS *************/

#define INI_Rename_Byt_BS_File() Rename = 0

#define Rename_VAL(v)       *(v) = Rename

#define Rename_STO(v)       Rename = (v)

#define Rename_INC()        Rename = Rename+1

#define Rename_DEC()        Rename = Rename-1

#define Rename_ADD(v)       Rename = Rename+(v)

#define Rename_SUB(v)       Rename = Rename-(v)

#define Rename_MUL(v)       Rename = Rename*(v)

#define Rename_DIV(v)       Rename = Rename/(v)

#define Rename_MOD(v)       Rename = Rename-( (v)*( (Rename)/(v) ))

#define Rename_LEFT()       Rename = (Rename)*2

#define Rename_RIGHT()      Rename = (Rename)/2

#define Rename_AND(v)       Rename = Rename&(v)

#define Rename_OR(v)        Rename = Rename|(v)

#define Rename_XOR(v)       Rename = Rename^(v)

#define Rename_NOT()        Rename = ~Rename

#define Rename_XTR(b,p)     { *(b) = ((Rename) & (1<<(p))) >> (p); }

#define Rename_SET(p,b) \
  { Rename = ( (b) ? ((Rename) | (1<<(p))) : (((Rename) | (1<<(p))) ^ (1<<(p))) ); }
