/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_UiRcdP1;
extern int Rename_UiRcdP2;
extern int Rename_UiRcdP3;

extern int Rename_UiRcd_ARR_UiArrP1;
extern int Rename_UiRcd_ARR_UiArrP2;
extern int Rename_UiRcd_ARR_UiArrP3;

extern int Rename_UiRcd_ARR[];

extern int Rename_UiRcd_HEAP_ARR_UiArrP1;
extern int Rename_UiRcd_HEAP_ARR_UiArrP2;
extern int Rename_UiRcd_HEAP_ARR_UiArrP3;

extern int Rename_UiRcd_HEAP_ARR[];

extern int Rename_UiRcd_TOT;

INI_Rename_UiRcd()
{
  {} ;
  {} ;
  Rename_UiRcd_TOT = 0 ;
  {
    int ii;
    ii = 0;
    while( ii<Rename_UiRcdP3 ){
      Rename_UiRcd_HEAP_ARR[ ii ] =  ii  ;
      *( &ii ) = ( ii )+1 ;
    };
    Rename_UiRcd_TOT =  0  ;
  }
}

Rename_UiRcd_RST()
{
  int ii;
  ii = 0;
  while( ii<Rename_UiRcdP3 ){
    Rename_UiRcd_HEAP_ARR[ ii ] =  ii  ;
    *( &ii ) = ( ii )+1 ;
  };
  Rename_UiRcd_TOT =  0  ;
}

/* ANSIC header */
Rename_UiRcd_IDX(int *bb, int idx)
/* end ANSIC header */

/* non-ANSIC header */
Rename_UiRcd_IDX(bb,idx)
int *bb,idx;
/* end non-ANSIC header */
{
  if( idx<=Rename_UiRcdP2 ){
    *bb = 1 ;
  } else {
    *bb = 0 ;
  }
}

/* ANSIC header */
Rename_UiRcd_FULL(int *bb)
/* end ANSIC header */

/* non-ANSIC header */
Rename_UiRcd_FULL(bb)
int *bb;
/* end non-ANSIC header */
{
  int vv;
  *( &vv ) = Rename_UiRcd_TOT ;
  if( vv == Rename_UiRcdP3 ){
    *bb = 1 ;
  } else {
    *bb = 0 ;
  }
}

/* ANSIC header */
Rename_UiRcd_CRE(int *rr)
/* end ANSIC header */

/* non-ANSIC header */
Rename_UiRcd_CRE(rr)
int *rr;
/* end non-ANSIC header */
{
  int ii,ss;
  *( &ii ) = Rename_UiRcd_TOT ;
  *( &ss ) = Rename_UiRcd_HEAP_ARR[ ii ] ;
  *( rr ) = ( ss )+1 ;
  Rename_UiRcd_TOT = Rename_UiRcd_TOT+1 ;
}

/* ANSIC header */
Rename_UiRcd_KILL(int rr)
/* end ANSIC header */

/* non-ANSIC header */
Rename_UiRcd_KILL(rr)
int rr;
/* end non-ANSIC header */
{
  int ii,ss;
  Rename_UiRcd_TOT = Rename_UiRcd_TOT-1 ;
  *( &ss ) = ( rr )-1 ;
  *( &ii ) = Rename_UiRcd_TOT ;
  Rename_UiRcd_HEAP_ARR[ ii ] =  ss  ;
}

/* ANSIC header */
Rename_UiRcd_VLD(int *bb, int rr)
/* end ANSIC header */

/* non-ANSIC header */
Rename_UiRcd_VLD(bb,rr)
int *bb,rr;
/* end non-ANSIC header */
{
  int tt,ii,aa,ss;
  *( &tt ) = Rename_UiRcd_TOT ;
  aa = 1 ;
  ii = Rename_UiRcdP3;
  while( aa == 1  && ii>tt ){
    *( &ii ) = ( ii )-1 ;
    *( &ss ) = Rename_UiRcd_HEAP_ARR[ ii ] ;
    *( &ss ) = ( ss )+1 ;
    if( rr == ss ){
      aa = 0 ;
    }
  };
  *bb = aa;
}

/* ANSIC header */
Rename_UiRcd_STO(int rr, int idx, int vv)
/* end ANSIC header */

/* non-ANSIC header */
Rename_UiRcd_STO(rr,idx,vv)
int rr,idx,vv;
/* end non-ANSIC header */
{
  int jj,kk;
  *( &jj ) = ( rr )-1 ;
  *( &kk ) = ( idx )-1 ;
  *( &jj ) = ( jj )*( Rename_UiRcdP2 ) ;
  *( &jj ) = ( jj )+( kk ) ;
  Rename_UiRcd_ARR[ jj ] =  vv  ;
}

/* ANSIC header */
Rename_UiRcd_VAL(int *vv, int rr, int idx)
/* end ANSIC header */

/* non-ANSIC header */
Rename_UiRcd_VAL(vv,rr,idx)
int *vv,rr,idx;
/* end non-ANSIC header */
{
  int jj,kk;
  *( &jj ) = ( rr )-1 ;
  *( &kk ) = ( idx )-1 ;
  *( &jj ) = ( jj )*( Rename_UiRcdP2 ) ;
  *( &jj ) = ( jj )+( kk ) ;
  *( vv ) = Rename_UiRcd_ARR[ jj ] ;
}
