/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_fstr_objP1;
extern int Rename_fstr_objP2;
extern int Rename_tot_fstr_obj;

extern int Rename_adr_fstr_obj[];
extern int Rename_ssiz_adr_fstr_obj;

extern int Rename_len_fstr_obj[];
extern int Rename_ssiz_len_fstr_obj;

extern int Rename_old_fstr_obj[];
extern int Rename_ssiz_old_fstr_obj;

extern char Rename_array_fstr_obj[];

char Rename_buf_fstr_obj[1000];


#define Rename_MEM_FUL_FSTR_OBJ(bb) \
{*(bb) = ((Rename_tot_fstr_obj == 0)!=0);}

#define Rename_OBJ_FUL_FSTR_OBJ(bb)     \
{*(bb) = ((Rename_ssiz_len_fstr_obj-1-Rename_ssiz_old_fstr_obj == Rename_fstr_objP1)!=0);}

#define Rename_FRE_MEM_FSTR_OBJ(nn) \
{*(nn) =  Rename_tot_fstr_obj;}

#define Rename_FRE_OBJ_FSTR_OBJ(nn)     \
{*(nn) = (Rename_fstr_objP1-Rename_ssiz_len_fstr_obj+1+Rename_ssiz_old_fstr_obj);}

#define Rename_ANY_FSTR_OBJ(nn)  \
{*(nn) = 1;}

#define Rename_XST_IDX_FSTR_OBJ(bb,pp,ii)   \
{*(bb) = ((ii>0) && (ii <= Rename_len_fstr_obj[pp]))!=0;}

#define Rename_CLR_FSTR_OBJ(ss) \
{Rename_tot_fstr_obj = Rename_tot_fstr_obj+Rename_len_fstr_obj[ss]; \
 Rename_len_fstr_obj[ss] = 0;}

#define Rename_KIL_FSTR_OBJ(pp) \
{Rename_CLR_FSTR_OBJ(pp); \
 Rename_ssiz_old_fstr_obj=Rename_ssiz_old_fstr_obj+1; \
 Rename_old_fstr_obj[Rename_ssiz_old_fstr_obj]=pp;}

#define Rename_STO_FSTR_OBJ(ss,ii,vv)  \
{Rename_array_fstr_obj[ii+Rename_adr_fstr_obj[ss]] = vv;}

#define Rename_VAL_FSTR_OBJ(vv,ss,ii)  \
{*(vv) = Rename_array_fstr_obj[ii+Rename_adr_fstr_obj[ss]];}

#define Rename_POP_FSTR_OBJ(pp)        \
{Rename_len_fstr_obj[pp] = Rename_len_fstr_obj[pp]-1; \
 Rename_tot_fstr_obj = Rename_tot_fstr_obj+1;}

#define Rename_KEP_FSTR_OBJ(pp,ii)      \
{Rename_tot_fstr_obj = Rename_tot_fstr_obj+Rename_len_fstr_obj[pp]-(ii); \
 Rename_len_fstr_obj[pp] = ii;}

#define Rename_LEN_FSTR_OBJ(nn,pp)     \
{*(nn) = Rename_len_fstr_obj[pp];}

#define Rename_EMP_FSTR_OBJ(bb,pp)   \
{*(bb) = (Rename_len_fstr_obj[pp]==0)!=0;}

void INI_Rename_fstr_obj();
void Rename_INI_FSTR_OBJ();
void Rename_XST_FSTR_OBJ();
void Rename_SAV_FSTR_OBJ();
void Rename_SAVN_FSTR_OBJ();
void Rename_RST_FSTR_OBJ();
void Rename_RSTN_FSTR_OBJ();
void Rename_CRE_FSTR_OBJ();
void Rename_PSH_FSTR_OBJ();
void Rename_SMR_FSTR_OBJ();
void Rename_EQL_FSTR_OBJ();
void Rename_EQL_LIT_FSTR_OBJ();
void Rename_NEW_FSTR_OBJ();
void Rename_XTR_FSTR_OBJ();
void Rename_APP_FSTR_OBJ();
void Rename_CPY_FSTR_OBJ();
void Rename_OVR_FSTR_OBJ();
void Rename_CUT_FSTR_OBJ();
void Rename_SWP_FSTR_OBJ();
void Rename_REV_FSTR_OBJ();
void Rename_FIRST_FSTR_OBJ();
void Rename_NEXT_FSTR_OBJ();
