/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_Utilities.h"

#define _chk_exist(a,b) \
  if ( stat ( a, &stat_buf ) == -1 ) { \
    if ( b ) printf ( "\n\n  %s: does not exist\n\n", a ); \
    else     printf ( "\n\n  %s: could not create\n\n", a ); \
    *_rep = 0; \
    return; \
  }

void
Rename_RestorePreviousData ( int * _rep, char * _sysname, int _op )
{
  char iedir   [ 100 ];
  char buf    [ 1000 ];
  struct stat stat_buf;
  time_t _t = time ( NULL );
  FILE * infofile;

  _chk_exist ( "IntegrityCheck.txt", 1 );
  sprintf ( iedir, "%d_IntegrityError", ( int ) _t );
  sprintf ( buf, "rm -fr %s", iedir );
  system ( buf );
  sprintf ( buf, "mkdir %s", iedir );
  system ( buf );
  sprintf ( buf, "cp IntegrityCheck.txt %s", iedir );
  system ( buf );
  sprintf ( buf, "cp TXT/*.txt %s", iedir );
  system ( buf );
  sprintf ( buf, "%d_IntegrityError_READ_ME", ( int ) _t );
  infofile = fopen ( buf, "w" );
  if ( fopen != NULL ) {
    fprintf ( infofile, "\n  Integrity error occurred on " );
    fclose ( infofile );
  }
  sprintf ( buf, "date >> %d_IntegrityError_READ_ME", ( int ) _t );
  system ( buf );
  fflush ( stdout );
  sprintf ( buf, "%d_IntegrityError_READ_ME", ( int ) _t );
  infofile = fopen ( buf, "a" );
  if ( fopen != NULL ) {
    fprintf ( infofile, "\n  The relevant IntegrityCheck.txt and object .txt files are\n  in the directory %s\n\n", iedir );
    fprintf ( infofile, "  The error seems to have been caused by op %d,\n  appearing in FILE_C/%sOpcodes.h as:\n\n    ", _op, _sysname );
    fclose ( infofile );
  }
  sprintf ( buf, "grep %d FILE_C/%sOpcodes.h >> %d_IntegrityError_READ_ME", _op, _sysname, ( int ) _t );
  system ( buf );
  sprintf ( buf, "%d_IntegrityError_READ_ME", ( int ) _t );
  infofile = fopen ( buf, "a" );
  if ( fopen != NULL ) {
    fprintf ( infofile, "\n  For the op history list, see `modOpHistory' in `Global.txt'\n\n" );
    fclose ( infofile );
  }

  *_rep = 1;
}
