/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <sys/types.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/signal.h>
#include <sys/socket.h>
#include <sys/resource.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <sys/utsname.h>
#include <sys/ioctl.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <netdb.h>
#include <syslog.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <errno.h>

#ifndef INADDR_NONE
#define INADDR_NONE  0xffffffff
#endif /* INADDR_NONE */

extern char * Rename_ClientP1[];
extern int Rename_ClientP2;
extern int Rename_ClientP3;

extern char * _out_buf;
extern int _out_buf_size;
extern int _out_buf_ptr;

extern char * _in_buf;
extern int _in_buf_size;
extern int _in_buf_ptr;
extern int _in_buf_len;


#define INI_Rename_Client()   { _out_buf_ptr = 4; _in_buf_ptr = 4; }

void Rename_INIT ( int * _rep, void * _ipaddress, int _port );
void Rename_CONNECT ( int * _rep );
void Rename_WRITE ( int * _rep );
void Rename_READ ( int * _rep, int * _pp );
void Rename_CLOSE ( int * _rep );
void Rename_GET_TOK ( int * _rep, int * _tok, int _toksize );
void Rename_GET_STR ( int * _rep, int * _ss );
void Rename_GET_FIL ( int * _rep, int * _filesize, int * _filename );
void Rename_PUT_TOK ( int * _rep, int _tok, int _toksize );
void Rename_PUT_STR ( int * _rep, int * _ss );
void Rename_GET_IN_PTR ( int * _ptr );
void Rename_SET_IN_PTR ( int _ptr );
void Rename_GET_OUT_PTR ( int * _ptr );
void Rename_SET_OUT_PTR ( int _ptr );
