/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_VseqP2;
extern int Rename_Vseq[];
extern int Rename_Vsize;

#define INI_Rename_Vseq()         {Rename_Vsize = 0;}

#define Rename_FUL_SEQ(bb)        \
{*(bb) = ((Rename_Vsize == Rename_VseqP2)!=0);}

#define Rename_XST_IDX_SEQ(bb,ii) {*(bb) = (((ii>0) && (ii <= Rename_Vsize))!=0);}
#define Rename_LEN_SEQ(nn)        {*(nn) = Rename_Vsize;}

#define Rename_CLR_SEQ()          {Rename_Vsize = 0;}

#define Rename_EMP_SEQ(bb)        {*(bb) = ((Rename_Vsize == 0)!=0);}

#define Rename_PSH_SEQ(vv)        \
{Rename_Vseq[Rename_Vsize+1] = vv; Rename_Vsize = Rename_Vsize+1;}

#define Rename_POP_SEQ()          {Rename_Vsize = Rename_Vsize-1;}
#define Rename_FST_SEQ(vv)        {*(vv) = Rename_Vseq[1];}
#define Rename_LST_SEQ(vv)        {*(vv) = Rename_Vseq[Rename_Vsize];}
#define Rename_KEP_SEQ(ii)        {Rename_Vsize = ii;}
#define Rename_VAL_SEQ(vv,ii)     {*(vv) = Rename_Vseq[ii];}
#define Rename_STO_SEQ(ii,vv)     {Rename_Vseq[ii] = vv;}

#define Rename_EQL_SEQ(bb,ii,vv)  {*(bb) = ((Rename_Vseq[ii]==vv)!=0);}
#define Rename_NEQ_SEQ(bb,ii,vv)  {*(bb) = ((Rename_Vseq[ii]!=vv)!=0);}

void Rename_SAV_SEQ();
void Rename_SAVN_SEQ();
void Rename_RST_SEQ();
void Rename_RSTN_SEQ();
void Rename_TAL_SEQ();
void Rename_CUT_SEQ();
void Rename_SWP_SEQ();
void Rename_SCH_LO_EQL_SEQ();
void Rename_SCH_LO_NEQ_SEQ();
void Rename_SCH_HI_EQL_SEQ();
void Rename_SCH_HI_NEQ_SEQ();
void Rename_REV_SEQ();
void Rename_RHT_SEQ();
void Rename_LFT_SEQ();
