/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern char * Rename_seq_objP1 [];
extern int Rename_seq_objP2;
extern int Rename_seq_objP3;
extern int Rename_tot_seq_obj;

extern int Rename_adr_seq_obj[];
extern int Rename_ssiz_adr_seq_obj;

extern int Rename_len_seq_obj[];
extern int Rename_ssiz_len_seq_obj;

extern int Rename_old_seq_obj[];
extern int Rename_ssiz_old_seq_obj;

extern int Rename_array_seq_obj[];

#define Rename_STS_SEQ_OBJ(mm,nn,pp,qq) \
{ \
  *(mm) = (Rename_seq_objP3) - Rename_tot_seq_obj; \
  *(nn) = (Rename_seq_objP3); \
  *(pp) = (Rename_ssiz_len_seq_obj-1-Rename_ssiz_old_seq_obj); \
  *(qq) = (Rename_seq_objP2); \
}

#define Rename_MEM_FUL_SEQ_OBJ(bb) \
{*(bb) = ((Rename_tot_seq_obj == 0)!=0);}

#define Rename_OBJ_FUL_SEQ_OBJ(bb)     \
{*(bb) = ((Rename_ssiz_len_seq_obj-1-Rename_ssiz_old_seq_obj == Rename_seq_objP2)!=0);}

#define Rename_FRE_MEM_SEQ_OBJ(nn) \
{*(nn) =  Rename_tot_seq_obj;}

#define Rename_FRE_OBJ_SEQ_OBJ(nn)     \
{*(nn) = (Rename_seq_objP2-Rename_ssiz_len_seq_obj+1+Rename_ssiz_old_seq_obj);}

#define Rename_ANY_SEQ_OBJ(nn)  \
{*(nn) = 1;}

#define Rename_XST_IDX_SEQ_OBJ(bb,pp,ii)   \
{*(bb) = ((ii>0) && (ii <= Rename_len_seq_obj[pp]))!=0;}

#define Rename_CLR_SEQ_OBJ(ss) \
{Rename_tot_seq_obj = Rename_tot_seq_obj+Rename_len_seq_obj[ss]; \
 Rename_len_seq_obj[ss] = 0;}

#define Rename_KIL_SEQ_OBJ(pp) \
{Rename_CLR_SEQ_OBJ(pp); \
 Rename_ssiz_old_seq_obj=Rename_ssiz_old_seq_obj+1; \
 Rename_old_seq_obj[Rename_ssiz_old_seq_obj]=pp;}

#define Rename_STO_SEQ_OBJ(ss,ii,vv)  \
{Rename_array_seq_obj[ii+Rename_adr_seq_obj[ss]] = vv;}

#define Rename_VAL_SEQ_OBJ(vv,ss,ii)  \
{*(vv) = Rename_array_seq_obj[ii+Rename_adr_seq_obj[ss]];}

#define Rename_POP_SEQ_OBJ(pp)        \
{Rename_len_seq_obj[pp] = Rename_len_seq_obj[pp]-1; \
 Rename_tot_seq_obj = Rename_tot_seq_obj+1;}

#define Rename_KEP_SEQ_OBJ(pp,ii)      \
       {Rename_tot_seq_obj = Rename_tot_seq_obj+Rename_len_seq_obj[pp]-(ii); \
        Rename_len_seq_obj[pp] = ii;}

#define Rename_LEN_SEQ_OBJ(nn,pp)     \
{*(nn) = Rename_len_seq_obj[pp];}

#define Rename_EMP_SEQ_OBJ(bb,pp)   \
{*(bb) = (Rename_len_seq_obj[pp]==0)!=0;}

void INI_Rename_seq_obj();
void Rename_SAV_SEQ_OBJ();
void Rename_SAVN_SEQ_OBJ();
void Rename_RST_SEQ_OBJ();
void Rename_RSTN_SEQ_OBJ();
void Rename_CRE_SEQ_OBJ();
void Rename_PSH_SEQ_OBJ();
void Rename_MBR_SEQ_OBJ();
void Rename_APP_SEQ_OBJ();
void Rename_CPY_SEQ_OBJ();
void Rename_CUT_SEQ_OBJ();
