/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_NseqP2;
extern int Rename_NseqP1;
extern int Rename_Nseq[];
extern int Rename_Nsize;

#define INI_Rename_Nseq()         {Rename_Nsize = 0;}

#define Rename_FUL_NSEQ(bb)        \
{*(bb) = ((Rename_Nsize == Rename_NseqP2)!=0);}

#define Rename_XST_IDX_NSEQ(bb,ii) {*(bb) = (((ii>0) && (ii <= Rename_Nsize))!=0);}
#define Rename_LEN_NSEQ(nn)        {*(nn) = Rename_Nsize;}

#define Rename_CLR_NSEQ()          {Rename_Nsize = 0;}

#define Rename_EMP_NSEQ(bb)        {*(bb) = ((Rename_Nsize == 0)!=0);}

#define Rename_PSH_NSEQ(vv)        \
{Rename_Nseq[Rename_Nsize+1] = vv; Rename_Nsize = Rename_Nsize+1;}

#define Rename_POP_NSEQ()          {Rename_Nsize = Rename_Nsize-1;}
#define Rename_FST_NSEQ(vv)        {*(vv) = Rename_Nseq[1];}
#define Rename_LST_NSEQ(vv)        {*(vv) = Rename_Nseq[Rename_Nsize];}
#define Rename_KEP_NSEQ(ii)        {Rename_Nsize = ii;}
#define Rename_VAL_NSEQ(vv,ii)     {*(vv) = Rename_Nseq[ii];}
#define Rename_STO_NSEQ(ii,vv)     {Rename_Nseq[ii] = vv;}
#define Rename_ADD_NSEQ(ii,vv)     {Rename_Nseq[ii] = Rename_Nseq[ii]+(vv);}
#define Rename_SUB_NSEQ(ii,vv)     {Rename_Nseq[ii] = Rename_Nseq[ii]-(vv);}
#define Rename_MUL_NSEQ(ii,vv)     {Rename_Nseq[ii] = Rename_Nseq[ii]*(vv);}
#define Rename_DIV_NSEQ(ii,vv)     {Rename_Nseq[ii] = Rename_Nseq[ii]/(vv);}

#define Rename_MOD_NSEQ(ii,vv) \
{Rename_Nseq[ii] = Rename_Nseq[ii]-(vv)*(Rename_Nseq[ii]/(vv));}

#define Rename_EQL_NSEQ(bb,ii,vv)  {*(bb) = ((Rename_Nseq[ii]==(vv))!=0);}
#define Rename_NEQ_NSEQ(bb,ii,vv)  {*(bb) = ((Rename_Nseq[ii]!=(vv))!=0);}
#define Rename_GTR_NSEQ(bb,ii,vv)  {*(bb) = ((Rename_Nseq[ii]> (vv))!=0);}
#define Rename_GEQ_NSEQ(bb,ii,vv)  {*(bb) = ((Rename_Nseq[ii]>=(vv))!=0);}
#define Rename_SMR_NSEQ(bb,ii,vv)  {*(bb) = ((Rename_Nseq[ii]< (vv))!=0);}
#define Rename_LEQ_NSEQ(bb,ii,vv)  {*(bb) = ((Rename_Nseq[ii]<=(vv))!=0);}

void Rename_SAV_NSEQ();
void Rename_SAVN_NSEQ();
void Rename_RST_NSEQ();
void Rename_RSTN_NSEQ();
void Rename_TAL_NSEQ();
void Rename_CUT_NSEQ();
void Rename_SWP_NSEQ();
void Rename_MAX_IDX_NSEQ();
void Rename_MIN_IDX_NSEQ();
void Rename_SCH_LO_EQL_NSEQ();
void Rename_SCH_LO_NEQ_NSEQ();
void Rename_SCH_LO_GEQ_NSEQ();
void Rename_SCH_LO_GTR_NSEQ();
void Rename_SCH_LO_LEQ_NSEQ();
void Rename_SCH_LO_SMR_NSEQ();
void Rename_SCH_HI_EQL_NSEQ();
void Rename_SCH_HI_NEQ_NSEQ();
void Rename_SCH_HI_GEQ_NSEQ();
void Rename_SCH_HI_GTR_NSEQ();
void Rename_SCH_HI_LEQ_NSEQ();
void Rename_SCH_HI_SMR_NSEQ();
void Rename_SRT_ASC_NSEQ();
void Rename_SRT_DSC_NSEQ();
void Rename_REV_NSEQ();
void Rename_RHT_NSEQ();
void Rename_LFT_NSEQ();
