/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_set.h"

#include <stdio.h>
#include <sys/types.h>
#include <netinet/in.h>

extern FILE *dump_file;

#define convert_arr_htonl(a,i,n) \
  j = i; \
  k = 0; \
  while ( k < n ) { \
    a [ j ] = htonl ( a [ j ] ); \
    j++; \
    k++; \
  }

#define convert_arr_ntohl(a,i,n) \
  j = i; \
  k = 0; \
  while ( k < n ) { \
    a [ j ] = ntohl ( a [ j ] ); \
    j++; \
    k++; \
  }

#define  write_fm(a,b)    fwrite(&a,sizeof(int),b,dump_file)

void
Rename_SAV_SET()
{
	write_fm(Rename_scrd,1);
	write_fm(Rename_sset[1],Rename_scrd);
}

void
Rename_SAVN_SET()
{
        int j, k;
	Rename_scrd = htonl ( Rename_scrd );
	write_fm(Rename_scrd,1);
	Rename_scrd = ntohl ( Rename_scrd );

	convert_arr_htonl(Rename_sset,1,Rename_scrd);
	write_fm(Rename_sset[1],Rename_scrd);
	convert_arr_ntohl(Rename_sset,1,Rename_scrd);
}


#define  read_fm(a,b)    fread(&a,sizeof(int),b,dump_file)

void
Rename_RST_SET()
{
	read_fm(Rename_scrd,1);
	read_fm(Rename_sset[1],Rename_scrd);
}

void
Rename_RSTN_SET()
{
        int j, k;
	read_fm(Rename_scrd,1);
	Rename_scrd = ntohl ( Rename_scrd );

	read_fm(Rename_sset[1],Rename_scrd);
	convert_arr_ntohl(Rename_sset,1,Rename_scrd);
}


void
#ifdef _BT_ANSIC
Rename_ENT_SET( int vv )
#else
Rename_ENT_SET( vv )
int vv;
#endif
{
	int i,j;
	i = 0;
	j = Rename_scrd;
	while( j!=i ){
		if( Rename_sset[j] == vv ){
			i = j;
		} else{
			j = j-1;
		};
	};
	if( j==0 ){
		Rename_sset[Rename_scrd+1] = vv;
		Rename_scrd = Rename_scrd+1;
	};
}


void
#ifdef _BT_ANSIC
Rename_RMV_SET( int vv )
#else
Rename_RMV_SET( vv )
int vv;
#endif
{
	int i,j;
	i = 0;
	j = Rename_scrd;
	while( j!=i ){
		if( Rename_sset[j] == vv ){
			i = j;
		} else{
			j = j-1;
		};
	};
	if( j!=0 ){
		Rename_sset[j] = Rename_sset[Rename_scrd];
		Rename_scrd = Rename_scrd-1;
	};
}


void
#ifdef _BT_ANSIC
Rename_MBR_SET( int *bb, int vv )
#else
Rename_MBR_SET( bb, vv )
int *bb;
int vv;
#endif
{
	int i,j;
	i = 0;
	j = Rename_scrd;
	while( j!=i ){
		if( Rename_sset[j] == vv ){
			i = j;
		} else{
			j = j-1;
		};
	};
	*bb = ((j != 0)!=0 );
}

