/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_Nfnc.h"

#include <stdio.h>
#include <sys/types.h>
#include <netinet/in.h>

extern FILE *dump_file;

#define convert_arr_htonl(a,i,n) \
  j = i; \
  k = 0; \
  while ( k < n ) { \
    a [ j ] = htonl ( a [ j ] ); \
    j++; \
    k++; \
  }

#define convert_arr_ntohl(a,i,n) \
  j = i; \
  k = 0; \
  while ( k < n ) { \
    a [ j ] = ntohl ( a [ j ] ); \
    j++; \
    k++; \
  }

#define  write_fm(a,b)    fwrite(&a,sizeof(int),b,dump_file)

void
Rename_SAV_NFNC()
{
	write_fm(Rename_Nfnc[1],Rename_NfncP2);
}

void
Rename_SAVN_NFNC()
{
        int j, k;
	convert_arr_htonl(Rename_Nfnc,1,Rename_NfncP2);
	write_fm(Rename_Nfnc[1],Rename_NfncP2);
	convert_arr_ntohl(Rename_Nfnc,1,Rename_NfncP2);
}


#define  read_fm(a,b)    fread(&a,sizeof(int),b,dump_file)

void
Rename_RST_NFNC()
{
	read_fm(Rename_Nfnc[1],Rename_NfncP2);
}

void
Rename_RSTN_NFNC()
{
        int j, k;
	read_fm(Rename_Nfnc[1],Rename_NfncP2);
	convert_arr_ntohl(Rename_Nfnc,1,Rename_NfncP2);
}


void
INI_Rename_Nfnc()
{
	int i;
	i = 1;
	while( i<= Rename_NfncP2 ){
		Rename_Nfnc[i] = 2147483647;
		i = i+1;
	};
}


void
#ifdef _BT_ANSIC
Rename_FREE_NFNC( int *b, int *v )
#else
Rename_FREE_NFNC( b, v )
int *b, *v;
#endif
{
	int i;
	i = Rename_NfncP2;
	*b = 0;
	*v = 1;
	while( i>= 0 ){
		if (Rename_Nfnc[i] == 2147483647) {
			*b = 1;
			*v = i;
			i = 0
			    ;
		};
		i = i-1;
	};
}
