/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_FileRefGen.h"
#include "Bool_TYPE.h"

void
Rename_GEN_NEW_FILE_REF_pad_nbrStr( int _nn, char * _ss )
{
  if ( _nn < 10 ) {
    sprintf ( _ss, "0000%d", _nn );
  } 
  else if ( _nn < 100 ) {
    sprintf ( _ss, "000%d", _nn );
  } 
  else if ( _nn < 1000 ) {
    sprintf ( _ss, "00%d", _nn );
  } 
  else if ( _nn < 10000 ) {
    sprintf ( _ss, "0%d", _nn );
  } 
  else {
    sprintf ( _ss, "%d", _nn );
  } 
}

void
Rename_GEN_NEW_FILE_REF ( char * _filePathA, char * _filePathB, char * _filePathC, int * _updatedYear, int * _updatedRefNo, char * _refString, int _year, int _refNo )
{
  time_t       _tt;
  int          _mm;
  struct tm *  _tm_struct;
  char         _month_str [ 5 ];
  char         _nbr_str [ 10 ];

  _tt = time ( NULL );
  _tm_struct = localtime ( &_tt );

  _mm = _tm_struct->tm_mon + 1;
  if   ( _mm < 10 ) sprintf ( _month_str, "0%d", _mm );
  else              sprintf ( _month_str, "%d", _mm );

  * _updatedYear = _tm_struct->tm_year + 1900;

  * _updatedRefNo = _refNo;

  if   ( ( * _updatedRefNo < INT_MAX ) && ( * _updatedYear == _year ) ) * _updatedRefNo += 1;
  else                                                                  * _updatedRefNo = 1;
  Rename_GEN_NEW_FILE_REF_pad_nbrStr ( * _updatedRefNo, _nbr_str );
  sprintf ( _filePathA, "%s/%d_%s/%s",  _refString, * _updatedYear, _month_str, _nbr_str );

  if   ( * _updatedRefNo < INT_MAX ) * _updatedRefNo += 1;
  else                               * _updatedRefNo = 1;
  Rename_GEN_NEW_FILE_REF_pad_nbrStr ( * _updatedRefNo, _nbr_str );
  sprintf ( _filePathB, "%s/%d_%s/%s",  _refString, * _updatedYear, _month_str, _nbr_str );

  if   ( * _updatedRefNo < INT_MAX ) * _updatedRefNo += 1;
  else                               * _updatedRefNo = 1;
  Rename_GEN_NEW_FILE_REF_pad_nbrStr ( * _updatedRefNo, _nbr_str );
  sprintf ( _filePathC, "%s/%d_%s/%s",  _refString, * _updatedYear, _month_str, _nbr_str );
}

/*
void
Rename_GEN_BACKUP_FILE_REF ( char * _newFilePath, int * _updatedYear, int * _updatedRefNo, char * _filePath, int _year, int _refNo )
{
  #define _refStringMAX 100
  char _refString [ _refStringMAX + 1 ];
  int _ii = 0;
  
  while ( ( _ii < _refStringMAX ) && ( _filePath [ _ii ] != '/' ) && ( _filePath [ _ii ] != '\0' ) ) {
    _refString [ _ii ] = _filePath [ _ii ];
    _ii++;
  }
  _refString [ _ii ] = '\0';

  Rename_GEN_NEW_FILE_REF ( _newFilePath, _updatedYear, _updatedRefNo, _refString, _year, _refNo );
}
*/
