/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_BiBArrP1;
extern int Rename_BiBArrP2;
extern int Rename_BiBArrP3;

#include "Rename_B_BiArr.h"
#include "Rename_N_Byt.h"

void INI_Rename_BiBArr(void);
void Rename_BiBA_IDX(int *_bb,int _idx);
void Rename_BiBA_VAL(int *_vv,int _idx);
void Rename_BiBA_STO(int _idx,int _vv);
void Rename_BiBA_EQ(int *_bb,int _idx,int _vv);
void Rename_BiBA_IEQ(int *_bb,int _idx,int _idx2);
void Rename_BiBA_NE(int *_bb,int _idx,int _vv);
void Rename_BiBA_INE(int *_bb,int _idx,int _idx2);
void Rename_BiBA_GT(int *_bb,int _idx,int _vv);
void Rename_BiBA_IGT(int *_bb,int _idx,int _idx2);
void Rename_BiBA_GE(int *_bb,int _idx,int _vv);
void Rename_BiBA_IGE(int *_bb,int _idx,int _idx2);
void Rename_BiBA_LT(int *_bb,int _idx,int _vv);
void Rename_BiBA_ILT(int *_bb,int _idx,int _idx2);
void Rename_BiBA_LE(int *_bb,int _idx,int _vv);
void Rename_BiBA_ILE(int *_bb,int _idx,int _idx2);
void Rename_BiBA_ADD(int _idx,int _vv);
void Rename_BiBA_IADD(int _idx,int _idx2);
void Rename_BiBA_SUB(int _idx,int _vv);
void Rename_BiBA_ISUB(int _idx,int _idx2);
void Rename_BiBA_INC(int _idx);
void Rename_BiBA_DEC(int _idx);
void Rename_BiBA_MUL(int _idx,int _vv);
void Rename_BiBA_DIV(int _idx,int _vv);
void Rename_BiBA_REM(int _idx,int _vv);
void Rename_BiBA_STO_NXT(int _vv);
void Rename_BiBA_FILL(int _vv);
void Rename_BiBA_NXT(int *_nn);
