/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "Rename_str_obj.h"
#include "basic_io.h"

void
INI_Rename_str_obj()
{
	Rename_ssiz_adr_str_obj = 0;
	Rename_ssiz_len_str_obj = 0;
	Rename_adr_str_obj[Rename_ssiz_adr_str_obj+1] = 0;
	Rename_ssiz_adr_str_obj = Rename_ssiz_adr_str_obj+1;
	Rename_adr_str_obj[Rename_ssiz_adr_str_obj+1] = Rename_str_objP2;
	Rename_ssiz_adr_str_obj = Rename_ssiz_adr_str_obj+1;
	Rename_len_str_obj[Rename_ssiz_len_str_obj+1] = 0;
	Rename_ssiz_len_str_obj = Rename_ssiz_len_str_obj+1;
	Rename_tot_str_obj = Rename_str_objP2;
	Rename_ssiz_old_str_obj = 0;
}


void
Rename_INI_STR_OBJ()
{
	Rename_ssiz_adr_str_obj = 0;
	Rename_ssiz_len_str_obj = 0;
	Rename_adr_str_obj[Rename_ssiz_adr_str_obj+1] = 0;
	Rename_ssiz_adr_str_obj = Rename_ssiz_adr_str_obj+1;
	Rename_adr_str_obj[Rename_ssiz_adr_str_obj+1] = Rename_str_objP2;
	Rename_ssiz_adr_str_obj = Rename_ssiz_adr_str_obj+1;
	Rename_len_str_obj[Rename_ssiz_len_str_obj+1] = 0;
	Rename_ssiz_len_str_obj = Rename_ssiz_len_str_obj+1;
	Rename_tot_str_obj = Rename_str_objP2;
	Rename_ssiz_old_str_obj = 0;
}


void
#ifdef _BT_ANSIC
Rename_XST_STR_OBJ( int *bb, int pp )
#else
Rename_XST_STR_OBJ( bb, pp )
int *bb, pp;
#endif
{
	if ( pp > 0 && pp < Rename_ssiz_len_str_obj ) {
		int i;
		i = Rename_ssiz_old_str_obj;
		*bb = 1;
		while ( i != 0 ) {
			if ( pp != Rename_old_str_obj[i] ) {
				i = i - 1;
			} else {
				i = 0 ;
				*bb = 0;
			}
		}
	} else {
		*bb=0;
	}
}

#include <stdio.h>
#include <sys/types.h>
#include <netinet/in.h>

extern FILE *dump_file;

#define convert_arr_htonl(a,i,n) \
  j = i; \
  k = 0; \
  while ( k < n ) { \
    a [ j ] = htonl ( a [ j ] ); \
    j++; \
    k++; \
  }

#define convert_arr_ntohl(a,i,n) \
  j = i; \
  k = 0; \
  while ( k < n ) { \
    a [ j ] = ntohl ( a [ j ] ); \
    j++; \
    k++; \
  }

#define  write_fm(a,b)    fwrite(&a,sizeof(int),b,dump_file)

#define  write_fmc(a,b)    fwrite(&a,sizeof(char),b,dump_file)

void
Rename_SAV_STR_OBJ()
{
	int i;
	char c;
        Rename_tot_str_obj = Rename_str_objP2-Rename_tot_str_obj;
	write_fm(Rename_tot_str_obj,1);
	write_fm(Rename_ssiz_adr_str_obj,1);
	write_fm(Rename_adr_str_obj[1],Rename_ssiz_adr_str_obj);
	write_fm(Rename_ssiz_len_str_obj,1);
	write_fm(Rename_len_str_obj[1],Rename_ssiz_len_str_obj);
	write_fm(Rename_ssiz_old_str_obj,1);
	write_fm(Rename_old_str_obj[1],Rename_ssiz_old_str_obj);
	write_fmc(Rename_array_str_obj[1],Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1]);
	i = Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1] % 4;
	c = 'w';
	while( i!=0 ){
		write_fmc(c,1);
		i = i-1;
	}
        Rename_tot_str_obj = Rename_str_objP2-Rename_tot_str_obj;
}

void
Rename_SAVN_STR_OBJ()
{
	int i, j, k;
	char c;
        Rename_tot_str_obj = Rename_str_objP2-Rename_tot_str_obj;

	Rename_tot_str_obj = htonl ( Rename_tot_str_obj );
        write_fm(Rename_tot_str_obj,1);
	Rename_tot_str_obj = ntohl ( Rename_tot_str_obj );

	Rename_ssiz_adr_str_obj = htonl ( Rename_ssiz_adr_str_obj );
	write_fm(Rename_ssiz_adr_str_obj,1);
	Rename_ssiz_adr_str_obj = ntohl ( Rename_ssiz_adr_str_obj );

	convert_arr_htonl(Rename_adr_str_obj,1,Rename_ssiz_adr_str_obj);
	write_fm(Rename_adr_str_obj[1],Rename_ssiz_adr_str_obj);
	convert_arr_ntohl(Rename_adr_str_obj,1,Rename_ssiz_adr_str_obj);

	Rename_ssiz_len_str_obj = htonl ( Rename_ssiz_len_str_obj );
	write_fm(Rename_ssiz_len_str_obj,1);
	Rename_ssiz_len_str_obj = ntohl ( Rename_ssiz_len_str_obj );

	convert_arr_htonl(Rename_len_str_obj,1,Rename_ssiz_len_str_obj);
	write_fm(Rename_len_str_obj[1],Rename_ssiz_len_str_obj);
	convert_arr_ntohl(Rename_len_str_obj,1,Rename_ssiz_len_str_obj);

	Rename_ssiz_old_str_obj = htonl ( Rename_ssiz_old_str_obj );
	write_fm(Rename_ssiz_old_str_obj,1);
	Rename_ssiz_old_str_obj = ntohl ( Rename_ssiz_old_str_obj );

	convert_arr_htonl(Rename_old_str_obj,1,Rename_ssiz_old_str_obj);
	write_fm(Rename_old_str_obj[1],Rename_ssiz_old_str_obj);
	convert_arr_ntohl(Rename_old_str_obj,1,Rename_ssiz_old_str_obj);

	write_fmc(Rename_array_str_obj[1],Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1]);
	/* padding ? */
	i = Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1] % 4;
	c = 'w';
	while( i!=0 ){
		write_fmc(c,1);
		i = i-1;
	}

        Rename_tot_str_obj = Rename_str_objP2-Rename_tot_str_obj;
}


#define  read_fm(a,b)    fread(&a,sizeof(int),b,dump_file)

#define  read_fmc(a,b)   fread(&a,sizeof(char),b,dump_file)

void
Rename_RST_STR_OBJ()
{
	int i;
	char c;
	read_fm(Rename_tot_str_obj,1);
	read_fm(Rename_ssiz_adr_str_obj,1);
	read_fm(Rename_adr_str_obj[1],Rename_ssiz_adr_str_obj);
	read_fm(Rename_ssiz_len_str_obj,1);
	read_fm(Rename_len_str_obj[1],Rename_ssiz_len_str_obj);
	read_fm(Rename_ssiz_old_str_obj,1);
	read_fm(Rename_old_str_obj[1],Rename_ssiz_old_str_obj);
	read_fmc(Rename_array_str_obj[1],Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1]);
	i = Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1] % 4;
	while( i!=0 ){
		read_fmc(c,1);
		i = i-1;
	}
        Rename_tot_str_obj = Rename_str_objP2-Rename_tot_str_obj;
        Rename_adr_str_obj[Rename_ssiz_adr_str_obj] = Rename_str_objP2;
}

void
Rename_RSTN_STR_OBJ()
{
	int i, j, k;
	char c;
	read_fm(Rename_tot_str_obj,1);
	Rename_tot_str_obj = ntohl ( Rename_tot_str_obj );

	read_fm(Rename_ssiz_adr_str_obj,1);
	Rename_ssiz_adr_str_obj = ntohl ( Rename_ssiz_adr_str_obj );

	read_fm(Rename_adr_str_obj[1],Rename_ssiz_adr_str_obj);
	convert_arr_ntohl(Rename_adr_str_obj,1,Rename_ssiz_adr_str_obj);

	read_fm(Rename_ssiz_len_str_obj,1);
	Rename_ssiz_len_str_obj = ntohl ( Rename_ssiz_len_str_obj );

	read_fm(Rename_len_str_obj[1],Rename_ssiz_len_str_obj);
	convert_arr_ntohl(Rename_len_str_obj,1,Rename_ssiz_len_str_obj);

	read_fm(Rename_ssiz_old_str_obj,1);
	Rename_ssiz_old_str_obj = ntohl ( Rename_ssiz_old_str_obj );

	read_fm(Rename_old_str_obj[1],Rename_ssiz_old_str_obj);
	convert_arr_ntohl(Rename_old_str_obj,1,Rename_ssiz_old_str_obj);

	read_fmc(Rename_array_str_obj[1],Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1]);
	/* padding ? */
	i = Rename_adr_str_obj[Rename_ssiz_adr_str_obj-1] % 4;
	while( i!=0 ){
		read_fmc(c,1);
		i = i-1;
	}

        Rename_tot_str_obj = Rename_str_objP2-Rename_tot_str_obj;
        Rename_adr_str_obj[Rename_ssiz_adr_str_obj] = Rename_str_objP2;
}


void
#ifdef _BT_ANSIC
Rename_CRE_STR_OBJ( int *bb, int *pp )
#else
Rename_CRE_STR_OBJ( bb, pp )
int *bb, *pp;
#endif
{
	int b;
	Rename_OBJ_FUL_STR_OBJ(&b);
	if( b==0 ){
		if( Rename_ssiz_old_str_obj==0 ){
			Rename_adr_str_obj[Rename_ssiz_len_str_obj+1] = 
			    Rename_adr_str_obj[Rename_ssiz_len_str_obj];
			Rename_adr_str_obj[Rename_ssiz_adr_str_obj+1] =
                                                             Rename_str_objP2;
			Rename_ssiz_adr_str_obj = Rename_ssiz_adr_str_obj+1;
			Rename_len_str_obj[Rename_ssiz_len_str_obj+1] = 0;
			Rename_ssiz_len_str_obj = Rename_ssiz_len_str_obj+1;
			*pp = Rename_ssiz_len_str_obj-1;
		} else {
			*pp=Rename_old_str_obj[Rename_ssiz_old_str_obj];
			Rename_ssiz_old_str_obj=Rename_ssiz_old_str_obj-1;
		}
		*bb=1;
	} else {
		*pp=0;
		*bb=0;
	}
}


void
#ifdef _BT_ANSIC
Rename_PSH_STR_OBJ( int *bb, int ss, int vv )
#else
Rename_PSH_STR_OBJ( bb, ss, vv )
int *bb, ss, vv;
#endif
{
	int e;
	Rename_MEM_FUL_STR_OBJ(&e);
	if( e==0 ){
		int search_res,y,k,r;
		r = 1;
		y = Rename_ssiz_adr_str_obj+1;
		search_res = 0;
		while( y!=r ){
			if( Rename_ssiz_adr_str_obj>2*ss-1 ){
				if( r<=2*ss-1 ){
					if( (r-1)%2 == 0 ){
						k = ss - (r/2);
					} else {
						k = ss + (r/2);
					}
				} else {
					k = r;
				}
			} else {
				if( r<=2*(Rename_ssiz_adr_str_obj-ss) ){
					if( (r-1)%2 == 0 ){
						k =ss - (r/2);
					} else {
						k = ss + (r/2);
					}
				} else {
					k = Rename_ssiz_adr_str_obj+1-r;
				}
			}
			if( Rename_adr_str_obj[k]+Rename_len_str_obj[k]<
                                                     Rename_adr_str_obj[k+1] ){
				y = r;
				search_res = k;
			} else {
				r = r+1;
			}
		}
		if( ss<search_res ){
			int j,a,b;
			j = search_res;
			while( j>ss ){
				a = Rename_adr_str_obj[j];
				b = Rename_len_str_obj[j];
				{
					int k;
					k=a+b;
					while( k>a ){
						Rename_array_str_obj[k+1]=
                                                        Rename_array_str_obj[k];
						k=k-1;
					}
				}
				Rename_adr_str_obj[j] = Rename_adr_str_obj[j]+1;
				j = j-1;
			}
		} else {
			int j,a,b;
			j = search_res+1;
			while( j<=ss ){
				a = Rename_adr_str_obj[j];
				b = Rename_len_str_obj[j];
				{
					int k;
					k=a+1;
					while( k<=a+b ){
						Rename_array_str_obj[k-1]=
                                                         Rename_array_str_obj[k];
						k=k+1;
					}
				}
				Rename_adr_str_obj[j] = Rename_adr_str_obj[j]-1;
				j = j+1;
			}
		}
		Rename_len_str_obj[ss] = Rename_len_str_obj[ss]+1;
		Rename_tot_str_obj = Rename_tot_str_obj-1;
		Rename_array_str_obj[Rename_len_str_obj[ss]+Rename_adr_str_obj[ss]] = vv;
	}
	*bb=!e;
}


void
#ifdef _BT_ANSIC
Rename_SMR_STR_OBJ( int *bb, int ss, int tt )
#else
Rename_SMR_STR_OBJ( bb, ss, tt )
int *bb, ss, tt;
#endif
{
	int m,n,i,v,w;
	m = Rename_len_str_obj[ss];
	n = Rename_len_str_obj[tt];
	if( m<=n ){
		i = 1;
		*bb = 1;
		while( i<=m ){
			v = Rename_array_str_obj[i+Rename_adr_str_obj[ss]];
			w = Rename_array_str_obj[i+Rename_adr_str_obj[tt]];
			if( v<w ){
				i = m+1;
				*bb = 1;
			} else if( w<v ){
				i = m+1;
				*bb = 0;
			} else {
				i = i+1;
			}
		}
	} else {
		i = 1;
		*bb = 0;
		while( i<=n ){
			v = Rename_array_str_obj[i+Rename_adr_str_obj[ss]];
			w = Rename_array_str_obj[i+Rename_adr_str_obj[tt]];
			if( v<w ){
				i = n+1;
				*bb = 1;
			} else if( w<v ){
				i = n+1;
				*bb = 0;
			} else {
				i = i+1;
			}
		}
	}
}


void
#ifdef _BT_ANSIC
Rename_EQL_STR_OBJ( int *bb, int ss, int tt )
#else
Rename_EQL_STR_OBJ( bb, ss, tt )
int *bb, ss, tt;
#endif
{
	int m,n,i,v,w;
	m = Rename_len_str_obj[ss];
	n = Rename_len_str_obj[tt];
	if( m==n ){
		i = 1;
		*bb = 1;
		while( i<=m ){
			v = Rename_array_str_obj[i+Rename_adr_str_obj[ss]];
			w = Rename_array_str_obj[i+Rename_adr_str_obj[tt]];
			if( v!=w ){
				i = m+1;
				*bb = 0;
			} else {
				i = i+1;
			}
		}
	} else {
		*bb = 0;
	}
}


void
#ifdef _BT_ANSIC
Rename_SUB_STR_OBJ( int *bb, int ss, int tt )
#else
Rename_SUB_STR_OBJ( bb, ss, tt )
int *bb, ss, tt;
#endif
{
	int m,n,i,v,w;
	m = Rename_len_str_obj[ss];
	n = Rename_len_str_obj[tt];
	if( m<=n ){
		i = 1;
		*bb = 1;
		while( i<=m ){
			v = Rename_array_str_obj[i+Rename_adr_str_obj[ss]];
			w = Rename_array_str_obj[i+Rename_adr_str_obj[tt]];
			if( v!=w ){
				i = m+1;
				*bb = 0;
			} else {
				i = i+1;
			}
		}
	} else {
		*bb = 0;
	}
}


void
#ifdef _BT_ANSIC
Rename_EQL_LIT_STR_OBJ( int *bb, int tt, int *nn )
#else
Rename_EQL_LIT_STR_OBJ( bb, tt, nn )
int *bb, tt, *nn;
#endif
{
	int m,n,i,v,w;
	char *ss;
	ss = (char *)nn;
	m = 0;
	while( ss[m]!='\0' ){
		m = m+1;
	}
	n = Rename_len_str_obj[tt];
	if( m==n ){
		i = 1;
		*bb = 1;
		while( i<=m ){
			v = ss[i-1];
			w = Rename_array_str_obj[i+Rename_adr_str_obj[tt]];
			if( v!=w ){
				i = m+1;
				*bb = 0;
			} else {
				i = i+1;
			}
		}
	} else {
		*bb = 0;
	}
}


void
#ifdef _BT_ANSIC
Rename_NEW_STR_OBJ( int *bb, int *pp, int *nn )
#else
Rename_NEW_STR_OBJ( bb, pp, nn )
int *bb, *pp, *nn;
#endif
{
	int b,i,p;
	char *ss;
	ss = (char *)nn;
	Rename_CRE_STR_OBJ(&b,&p);
	if( b==1 ){
		i=0;
		while( (ss[i]!='\0') && (b==1) ){
			Rename_PSH_STR_OBJ(&b,p,ss[i]);
			i=i+1;
		}
		if( b==1 ){
			*pp = p;
			*bb = 1;
		} else {
			Rename_KIL_STR_OBJ(p);
			*pp = 0;
			*bb = 0;
		}
	} else {
		*pp = 0;
		*bb = b;
	}
}


void
#ifdef _BT_ANSIC
Rename_XTR_STR_OBJ( int *ss, int pp )
#else
Rename_XTR_STR_OBJ( ss, pp )
int *ss, pp;
#endif
{
	int i,v,s;
	char *t;
	t = (char *)ss;
	i = 0;
	s = Rename_len_str_obj[pp];
	while( i<s ){
		Rename_VAL_STR_OBJ(&v,pp,i+1);
		t[i] = v;
		i = i+1;
	}
	t[i] = '\0';
}


void
#ifdef _BT_ANSIC
Rename_APP_STR_OBJ( int *bb, int ss, int tt )
#else
Rename_APP_STR_OBJ( bb, ss, tt )
int *bb, ss, tt;
#endif
{
	int k,v,s,b,n;
	b=1;
	k=1;
	s=Rename_len_str_obj[tt];
	Rename_FRE_MEM_STR_OBJ(&n);
	if( s<=n ){
		while( k<=s ){
			Rename_VAL_STR_OBJ(&v,tt,k);
			Rename_PSH_STR_OBJ(&b,ss,v);
			k = k+1;
		}
		*bb=1;
	} else {
		*bb=0;
	}
}


void
#ifdef _BT_ANSIC
Rename_CPY_STR_OBJ(int * bb,int  ss, int tt )
#else
Rename_CPY_STR_OBJ( bb, ss, tt )
int *bb, ss, tt;
#endif
{
	int s,t,n;
	if( ss!=tt ){
		s = Rename_len_str_obj[ss];
		t = Rename_len_str_obj[tt];
		Rename_FRE_MEM_STR_OBJ(&n);
		if( s<=n+t ){
			Rename_CLR_STR_OBJ(tt);
			Rename_APP_STR_OBJ(&(*bb),tt,ss);
			*bb = 1;
		} else {
			*bb = 0;
		}
	} else {
		*bb = 1;
	}
}


/* ss over-written by tt */

void
#ifdef _BT_ANSIC
Rename_OVR_STR_OBJ( int *bb, int ss, int tt )
#else
Rename_OVR_STR_OBJ( bb, ss, tt )
int *bb, ss, tt;
#endif
{
	int s,t,n,i,v,b;
	if( ss!=tt ){
		s = Rename_len_str_obj[ss];
		t = Rename_len_str_obj[tt];
		Rename_FRE_MEM_STR_OBJ(&n);
		if( t<=n+s ){
			i = 1;
			while( i<=t ){
				Rename_VAL_STR_OBJ(&v,tt,i);
				if( i<=s ){
					Rename_STO_STR_OBJ(ss,i,v);
				} else {
					Rename_PSH_STR_OBJ(&b,ss,v);
				}
				i = i+1;
			}
			*bb = 1;
		} else {
			*bb = 0;
		}
	} else {
		*bb = 1;
	}
}


void
#ifdef _BT_ANSIC
Rename_CUT_STR_OBJ( int pp, int ii )
#else
Rename_CUT_STR_OBJ( pp, ii )
int pp, ii;
#endif
{
	int i,l,v;
	i = ii+1;
	Rename_LEN_STR_OBJ(&l,pp);
	while( i<=l ){
		Rename_VAL_STR_OBJ(&v,pp,i);
		Rename_STO_STR_OBJ(pp,i-ii,v);
		i = i+1
		    ;
	}
	Rename_len_str_obj[pp] = Rename_len_str_obj[pp]-ii;
	Rename_tot_str_obj = Rename_tot_str_obj+ii;
}


void
#ifdef _BT_ANSIC
Rename_SWP_STR_OBJ( int ss, int ii, int jj )
#else
Rename_SWP_STR_OBJ( ss, ii, jj )
int ss, ii, jj;
#endif
{
	int v,w;
	Rename_VAL_STR_OBJ(&v,ss,ii);
	Rename_VAL_STR_OBJ(&w,ss,jj);
	Rename_STO_STR_OBJ(ss,jj,v);
	Rename_STO_STR_OBJ(ss,ii,w);
}


void
#ifdef _BT_ANSIC
Rename_REV_STR_OBJ( int ss )
#else
Rename_REV_STR_OBJ( ss )
int ss;
#endif
{
	int i,j;
	i=1;
	Rename_LEN_STR_OBJ(&j,ss);
	while( i<j ){
		Rename_SWP_STR_OBJ(ss,i,j);
		i=i+1;
		j=j-1;
	}
}


void
#ifdef _BT_ANSIC
Rename_FIRST_STR_OBJ( int *cc, int *ss )
#else
Rename_FIRST_STR_OBJ( cc, ss )
int *cc, *ss;
#endif
{
	int c,i,b;
	c = ( Rename_ssiz_len_str_obj - 1 - Rename_ssiz_old_str_obj );
	if ( c != 0 ) {
		i = Rename_ssiz_len_str_obj - 1;
		Rename_XST_STR_OBJ(&b,i);
		while ( b != 1 && i != 0 ) {
			i = i - 1;
			Rename_XST_STR_OBJ(&b,i);
		}
		*ss = i;
		*cc = c;
	} else {
		*ss = 0;
		*cc = 0;
	}
}


void
#ifdef _BT_ANSIC
Rename_NEXT_STR_OBJ( int *cc, int *ss, int oc, int os )
#else
Rename_NEXT_STR_OBJ( cc, ss, oc, os )
int *cc, *ss, oc, os;
#endif
{
	int c,i,b;
	c = oc - 1;
	if ( c != 0 ) {
		i = os - 1;
		Rename_XST_STR_OBJ(&b,i);
		while ( b != 1 && i != 0 ) {
			i = i - 1;
			Rename_XST_STR_OBJ(&b,i);
		}
		*ss = i;
		*cc = c;
	} else {
		*ss = 0;
		*cc = 0;
	}

}
