/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_setP2;
extern int Rename_setP1;
extern int Rename_sset[];
extern int Rename_scrd;
#define INI_Rename_set()          {Rename_scrd = 0;}
#define Rename_CLR_SET()          {Rename_scrd = 0;}
#define Rename_FUL_SET(bb)        {*(bb) = \
                                  ((Rename_scrd == Rename_setP2)!=0);}
#define Rename_XST_IDX_SET(bb,ii) {*(bb) = ((ii <= Rename_scrd)!=0);}
#define Rename_CRD_SET(nn)        {*(nn) = Rename_scrd;}
#define Rename_VAL_SET(vv,ii)     {*(vv) = Rename_sset[ii];}
#define Rename_ANY_SET(vv)     {*(vv) = Rename_sset[1];}
#define Rename_EMP_SET(bb) {*(bb) = ((Rename_scrd == 0)!=0);}

void Rename_SAV_SET();
void Rename_SAVN_SET();
void Rename_RST_SET();
void Rename_RSTN_SET();
void Rename_ENT_SET();
void Rename_RMV_SET();
void Rename_MBR_SET();
