/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

extern int Rename_str_objP1;
extern int Rename_str_objP2;
extern int Rename_tot_str_obj;

extern int Rename_adr_str_obj[];
extern int Rename_ssiz_adr_str_obj;

extern int Rename_len_str_obj[];
extern int Rename_ssiz_len_str_obj;

extern int Rename_old_str_obj[];
extern int Rename_ssiz_old_str_obj;

extern char Rename_array_str_obj[];


#define Rename_STS_STR_OBJ(mm,nn,pp,qq) \
{ \
  *(mm) = (Rename_str_objP2) - (Rename_tot_str_obj); \
  *(nn) = (Rename_str_objP2); \
  *(pp) = (Rename_ssiz_len_str_obj-1-Rename_ssiz_old_str_obj); \
  *(qq) = (Rename_str_objP1); \
}

#define Rename_MEM_FUL_STR_OBJ(bb) \
{*(bb) = ((Rename_tot_str_obj == 0)!=0);}

#define Rename_OBJ_FUL_STR_OBJ(bb)     \
{*(bb) = ((Rename_ssiz_len_str_obj-1-Rename_ssiz_old_str_obj == Rename_str_objP1)!=0);}

#define Rename_FRE_MEM_STR_OBJ(nn) \
{*(nn) =  Rename_tot_str_obj;}

#define Rename_FRE_OBJ_STR_OBJ(nn)     \
{*(nn) = (Rename_str_objP1-Rename_ssiz_len_str_obj+1+Rename_ssiz_old_str_obj);}

#define Rename_ANY_STR_OBJ(nn)  \
{*(nn) = 1;}

#define Rename_XST_IDX_STR_OBJ(bb,pp,ii)   \
{*(bb) = ((ii>0) && (ii <= Rename_len_str_obj[pp]))!=0;}

#define Rename_CLR_STR_OBJ(ss) \
{Rename_tot_str_obj = Rename_tot_str_obj+Rename_len_str_obj[ss]; \
 Rename_len_str_obj[ss] = 0;}

#define Rename_KIL_STR_OBJ(pp) \
{Rename_CLR_STR_OBJ(pp); \
 Rename_ssiz_old_str_obj=Rename_ssiz_old_str_obj+1; \
 Rename_old_str_obj[Rename_ssiz_old_str_obj]=pp;}

#define Rename_STO_STR_OBJ(ss,ii,vv)  \
{Rename_array_str_obj[ii+Rename_adr_str_obj[ss]] = vv;}

#define Rename_VAL_STR_OBJ(vv,ss,ii)  \
{*(vv) = Rename_array_str_obj[ii+Rename_adr_str_obj[ss]];}

#define Rename_POP_STR_OBJ(pp)        \
{Rename_len_str_obj[pp] = Rename_len_str_obj[pp]-1; \
 Rename_tot_str_obj = Rename_tot_str_obj+1;}

#define Rename_KEP_STR_OBJ(pp,ii)      \
{Rename_tot_str_obj = Rename_tot_str_obj+Rename_len_str_obj[pp]-(ii); \
 Rename_len_str_obj[pp] = ii;}

#define Rename_LEN_STR_OBJ(nn,pp)     \
{*(nn) = Rename_len_str_obj[pp];}

#define Rename_EMP_STR_OBJ(bb,pp)   \
{*(bb) = (Rename_len_str_obj[pp]==0)!=0;}

#define Rename_REL_BUF_STR_OBJ() {}

void INI_Rename_str_obj();
void Rename_INI_STR_OBJ();
void Rename_XST_STR_OBJ();
void Rename_SAV_STR_OBJ();
void Rename_SAVN_STR_OBJ();
void Rename_RST_STR_OBJ();
void Rename_RSTN_STR_OBJ();
void Rename_CRE_STR_OBJ();
void Rename_PSH_STR_OBJ();
void Rename_SMR_STR_OBJ();
void Rename_EQL_STR_OBJ();
void Rename_SUB_STR_OBJ();
void Rename_EQL_LIT_STR_OBJ();
void Rename_NEW_STR_OBJ();
void Rename_XTR_STR_OBJ();
void Rename_APP_STR_OBJ();
void Rename_CPY_STR_OBJ();
void Rename_OVR_STR_OBJ();
void Rename_CUT_STR_OBJ();
void Rename_SWP_STR_OBJ();
void Rename_REV_STR_OBJ();
void Rename_FIRST_STR_OBJ();
void Rename_NEXT_STR_OBJ();
