/*Copyright (c) 1985-2012, B-Core (UK) Ltd

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#define UNSIGNED _Uns_TYPE_UNSIGNED

extern char * _Uns_TYPE_UNSIGNED [];


/*************** CONSTANTS *****************/ 

#define MinUns  0

#define MaxUns  65535

#define n2u(n)  (n)

#define u2n(n)  (n)

#define u2bs(n) (n)

#define bs2u(n) (n)

/*************** OPERATIONS *****************/

#define INI_Uns_BS_TYPE() { }

#define ULE(r,a,b)        *(r) = ((a<=b)!=0)

#define UGE(r,a,b)        *(r) = ((a>=b)!=0)

#define ULT(r,a,b)        *(r) = ((a< b)!=0)

#define UGT(r,a,b)        *(r) = ((a> b)!=0)

#define UEQ(r,a,b)        *(r) = ((a==b)!=0)

#define UNE(r,a,b)        *(r) = ((a!=b)!=0)

#define UADD(r,a,b)       *(r) = (a)+(b)

#define USUB(r,a,b)       *(r) = (a)-(b)

#define UMUL(r,a,b)       *(r) = (a)*(b)

#define UDIV(r,a,b)       *(r) = (a)/(b)

#define UMOD(r,a,b)       *(r) = (a)-( (b)*( (a)/(b) ))

#define UINC(r,a)         *(r) = (a)+1

#define UDEC(r,a)         *(r) = (a)-1

#define UAND(r,a,b)       *(r) = (a)&(b)

#define UOR(r,a,b)        *(r) = (a)|(b)

#define UXOR(r,a,b)       *(r) = (a)^(b)

#define UNOT(r,a)         *(r) = ~(a)
