#! /bin/csh -f

../UTIL/_rem_copied_to_c

cp ../BEESRC/itfmch.c.release ../BEESRC/itfmch.c
cp ../BEESRC/natmch.c.release ../BEESRC/natmch.c
cp ../BEESRC/filmch.c.release ../BEESRC/filmch.c
cp ../BEESRC/themch.c.release ../BEESRC/themch.c
cp ../BEESRC/prfmch.c.release ../BEESRC/prfmch.c
cp ../BEESRC/tolmch.c.release ../BEESRC/tolmch.c
cp ../BEESRC/symmch.c.release ../BEESRC/symmch.c
cp ../BEESRC/strmch.c.release ../BEESRC/strmch.c
cp ../BEESRC/lexmch.c.release ../BEESRC/lexmch.c
cp ../BEESRC/frmmch.c.release ../BEESRC/frmmch.c
cp ../BEESRC/errmch.c.release ../BEESRC/errmch.c
cp ../BEESRC/macmch.c.release ../BEESRC/macmch.c
cp ../BEESRC/rulmch.c.release ../BEESRC/rulmch.c
cp ../BEESRC/resmch.c.release ../BEESRC/resmch.c
cp ../BEESRC/hypmch.c.release ../BEESRC/hypmch.c
cp ../BEESRC/tacmch.c.release ../BEESRC/tacmch.c
cp ../BEESRC/nodmch.c.release ../BEESRC/nodmch.c
cp ../BEESRC/golmch.c.release ../BEESRC/golmch.c
cp ../BEESRC/seqmch.c.release ../BEESRC/seqmch.c
