#! /bin/csh -f

../UTIL/_rem_copied_to_c

cp ../BEESRC/itfmch.c.motif ../BEESRC/itfmch.c
cp ../BEESRC/natmch.c.motif ../BEESRC/natmch.c
cp ../BEESRC/filmch.c.motif ../BEESRC/filmch.c
cp ../BEESRC/themch.c.motif ../BEESRC/themch.c
cp ../BEESRC/prfmch.c.motif ../BEESRC/prfmch.c
cp ../BEESRC/tolmch.c.motif ../BEESRC/tolmch.c
cp ../BEESRC/symmch.c.motif ../BEESRC/symmch.c
cp ../BEESRC/strmch.c.motif ../BEESRC/strmch.c
cp ../BEESRC/lexmch.c.motif ../BEESRC/lexmch.c
cp ../BEESRC/frmmch.c.motif ../BEESRC/frmmch.c
cp ../BEESRC/errmch.c.motif ../BEESRC/errmch.c
cp ../BEESRC/macmch.c.motif ../BEESRC/macmch.c
cp ../BEESRC/rulmch.c.motif ../BEESRC/rulmch.c
cp ../BEESRC/resmch.c.motif ../BEESRC/resmch.c
cp ../BEESRC/hypmch.c.motif ../BEESRC/hypmch.c
cp ../BEESRC/tacmch.c.motif ../BEESRC/tacmch.c
cp ../BEESRC/nodmch.c.motif ../BEESRC/nodmch.c
cp ../BEESRC/golmch.c.motif ../BEESRC/golmch.c
cp ../BEESRC/seqmch.c.motif ../BEESRC/seqmch.c
