#! /bin/csh -f

#
# Install in $BKIT/BPALETTE
#

set curdir = `pwd`
cd ..

echo ""
echo "  -----------------------------------------------------"
echo "  This script copies from BPALETTE "
echo "  to  `pwd`/BKIT/BHELP "
echo "  -----------------------------------------------------"

cd $curdir

######################################
# set all variables 
######################################

source ./set_compile_variables

if ( $status != 0 ) then
  exit ( 1 )
endif

if ( ! -d $BKIT/BPALETTE ) then
  mkdir $BKIT/BPALETTE
endif

cd ../BPALETTE

echo ""

foreach file ( $PALETTE_files  )

  if ( ! -r $file ) then
    echo ""
    echo "            ----->>>>> $file does not exist - NOT COPIED"
    echo ""
    echo "            Aborted"
    echo ""
    exit ( 1 )
  else
    rm -f  $BKIT/BPALETTE/$file
    cp $file $BKIT/BPALETTE
    chmod 644 $BKIT/BPALETTE/$file
    echo ""
    echo "    $file -> $BKIT/BPALETTE "
  endif

end

echo ""
echo "  Done "
echo ""
