#! /bin/csh -f

echo ""
echo "  -----------------------------------------------------"
echo "  This script installs : "
echo "    `pwd`/BKIT/BLIB/BToolkit "
echo "  -----------------------------------------------------"

source ./set_compile_variables

cd ../C

echo ""
foreach file ( "BToolkit" )
  echo "  creating $BKIT/$file"
  echo "  $CC \ "
  echo "      $CC_opt_non_Motif \ "
  echo "      $file.c \ "
  echo "      -o $BKIT/$file \ "
  echo "      $ALL_FLAGS \ "
  echo "      $CC_non_X_link_lib"
  $CC \
      $CC_opt_non_Motif \
      $file.c \
      -o $BKIT/$file \
      $ALL_FLAGS \
      $CC_non_X_link_lib
  if ( $status != 0 ) then
    echo ""
    echo "                            >>>>> $file NOT COMPILED <<<<<"
  else
    echo "  strip $BKIT/$file >>>>>  SUPPRESSED <<<<<"
    #strip $BKIT/$file
  endif
  echo ""
end

echo ""
echo "  Done"
echo ""
