#! /bin/sh

if [ ! -r $1 ];
then
  printf "\n  Beditor:\n\n   %s\n\n  does not exist\n\n" $1
  exit 1
fi

EDITORS="$VISUAL nedit xedit textedit xemacs gvim gedit kedit"

for ed in $EDITORS
do

  got=`which $ed`

  if [ ! "$got" = "" ]
  then
     $got $1
     break
  fi

done
exit 0

