
HDRFILES = GlobalDefs.src Toolkit_core.src Utils.src AMNSYMBOL

#################################################################

  all : \
    $(BKIT)/BLIB/Toolkit1.bin \
    $(BKIT)/BLIB/Toolkit2.bin \
    $(BKIT)/BLIB/Toolkit3.bin \
    $(BKIT)/BLIB/Toolkit4.bin \
    $(BKIT)/BLIB/Toolkit5.bin \
    $(BKIT)/BLIB/Toolkit6.bin \
    $(BKIT)/BLIB/Toolkit7.bin \
    $(BKIT)/BLIB/Toolkit9.bin \
    $(BKIT)/BLIB/Toolkit13.bin \
    $(BKIT)/BLIB/Toolkit14.bin \
    $(BKIT)/BLIB/Toolkit15.bin \
    $(BKIT)/BLIB/Toolkit16.bin \
    $(BKIT)/BLIB/Toolkit20.bin \
    $(BKIT)/BLIB/Toolkit21.bin \
    $(BKIT)/BLIB/Toolkit24.bin \
    $(BKIT)/BLIB/Toolkit31.bin \
    $(BKIT)/BLIB/Toolkit32.bin \
    $(BKIT)/BLIB/Toolkit35.bin \
    $(BKIT)/BLIB/Toolkit36.bin \
    $(BKIT)/BLIB/Toolkit37.bin \
    $(BKIT)/BLIB/Toolkit38.bin \
    $(BKIT)/BLIB/Toolkit39.bin
	@echo
	@cd $(BKIT)/BLIB ; ls -l Toolkit*.bin
	@echo
	@echo "  make complete"
	@echo


    $(BKIT)/BLIB/Toolkit1.bin : $(HDRFILES) \
                                $(MR)/SRC/CreHtml.src \
                                $(MR)/SRC/Introduce.src \
                                $(MR)/SRC/Find.src \
                                $(MR)/SRC/Export.src \
                                $(MR)/SRC/Toolkit1.src
	$(HOME)/bin/install_bin 1 1


    $(BKIT)/BLIB/Toolkit2.bin : $(HDRFILES) \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CreHtml.src \
                                $(MR)/SRC/Desugarer.src \
                                $(MR)/SRC/Normaliser.src \
                                $(MR)/SRC/Analyser.src \
                                $(MR)/SRC/VHDLSyntax.src \
                                $(MR)/SRC/PASPSyntax.src \
                                $(MR)/SRC/MergeTypeAnlForm.src \
                                $(MR)/SRC/TypeChecker.src \
                                $(MR)/SRC/Toolkit2.src
	$(HOME)/bin/install_bin 2 1


    $(BKIT)/BLIB/Toolkit3.bin : $(HDRFILES) \
                                $(MR)/SRC/LoadUnloadProofMethod.src \
                                $(MR)/SRC/CreatePmdTemplate.src \
                                $(MR)/SRC/QueryUser.src \
                                $(MR)/SRC/AutoProver.src \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/SetOfRules_core \
                                $(MR)/SRC/SetOfRules_PASP \
                                $(MR)/SRC/SetOfRules_NonPASP \
                                $(MR)/SRC/MakeSetOfRules_FwdTheories.src \
                                $(MR)/SRC/MakeSetOfRules.src \
                                $(MR)/SRC/Toolkit3.src
	$(HOME)/bin/install_bin 3 1


    $(BKIT)/BLIB/Toolkit4.bin : $(HDRFILES) \
                                $(MR)/SRC/CreHtml.src \
                                $(MR)/SRC/Enum.src \
                                $(MR)/SRC/CIO_Common.src \
                                $(MR)/SRC/CIO.src \
                                $(MR)/SRC/CIOM.src \
                                $(MR)/SRC/Toolkit4.src
	$(HOME)/bin/install_bin 4 1


    $(BKIT)/BLIB/Toolkit5.bin : $(HDRFILES) \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/POGeneratorTheory.src \
                                $(MR)/SRC/POGPreProcessOps.src \
                                $(MR)/SRC/ExpandMachineOps.src \
                                $(MR)/SRC/POGenerator.src \
                                $(MR)/SRC/Toolkit5.src
	$(HOME)/bin/install_bin 5 1


    $(BKIT)/BLIB/Toolkit6.bin : $(HDRFILES) \
                                $(MR)/SRC/AMNSYMBOLD \
                                $(MR)/SRC/Latexer.src \
                                $(MR)/SRC/LatexProof.src \
                                $(MR)/SRC/Toolkit6.src
	$(HOME)/bin/install_bin 6 1


    $(BKIT)/BLIB/Toolkit7.bin : $(HDRFILES) \
                                $(MR)/SRC/Translators.src \
                                $(MR)/SRC/TransC.src \
                                $(MR)/SRC/Toolkit7.src
	$(HOME)/bin/install_bin 7 1


    $(BKIT)/BLIB/Toolkit9.bin : $(HDRFILES) \
                                $(MR)/SRC/ExpandMachineOps.src \
                                $(MR)/SRC/Animator.src \
                                $(MR)/SRC/Animator.thy \
                                $(MR)/SRC/Toolkit9.src
	$(HOME)/bin/install_bin 9 1


    $(BKIT)/BLIB/Toolkit13.bin : $(HDRFILES) \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/SetOfRules_core \
                                $(MR)/SRC/SetOfRules_PASP \
                                $(MR)/SRC/SetOfRules_NonPASP \
                                $(MR)/SRC/MakeSetOfRules_FwdTheories.src \
                                $(MR)/SRC/MakeSetOfRules.src \
                                $(MR)/SRC/Proof.src \
                                $(MR)/SRC/LoadUnloadProofMethod.src \
                                $(MR)/SRC/BToolProver.src \
                                $(MR)/SRC/Toolkit13.src
	$(HOME)/bin/install_bin 13 1


    $(BKIT)/BLIB/Toolkit14.bin : $(HDRFILES) \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/SetOfRules_core \
                                $(MR)/SRC/SetOfRules_PASP \
                                $(MR)/SRC/SetOfRules_NonPASP \
                                $(MR)/SRC/MakeSetOfRules_FwdTheories.src \
                                $(MR)/SRC/MakeSetOfRules.src \
                                $(MR)/SRC/Toolkit14.src
	$(HOME)/bin/install_bin 14 1


    $(BKIT)/BLIB/Toolkit15.bin : $(HDRFILES) \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/SetOfRules_core \
                                $(MR)/SRC/SetOfRules_PASP \
                                $(MR)/SRC/SetOfRules_NonPASP \
                                $(MR)/SRC/MakeSetOfRules_FwdTheories.src \
                                $(MR)/SRC/MakeSetOfRules_BTool.src
	$(HOME)/bin/install_bin 15 1


    $(BKIT)/BLIB/Toolkit16.bin : $(HDRFILES) \
                                $(MR)/SRC/ParseBaseExtSyntax.src \
                                $(MR)/SRC/GenBase.src \
                                $(MR)/SRC/GenBaseOps.src \
                                $(MR)/SRC/GenBaseMch.src \
                                $(MR)/SRC/GenBaseImp.src \
                                $(MR)/SRC/Toolkit16.src
	$(HOME)/bin/install_bin 16 1


    $(BKIT)/BLIB/Toolkit20.bin : $(HDRFILES) \
                                $(MR)/SRC/CreatePmdTemplate.src \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/POGeneratorTheory.src \
                                $(MR)/SRC/Toolkit2021.src \
                                $(MR)/SRC/POGeneratorS.src \
                                $(MR)/SRC/Toolkit20.src
	$(HOME)/bin/install_bin 20 1


    $(BKIT)/BLIB/Toolkit21.bin : $(HDRFILES) \
                                $(MR)/SRC/CreatePmdTemplate.src \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/POGeneratorTheory.src \
                                $(MR)/SRC/Toolkit2021.src \
                                $(MR)/SRC/POGeneratorR.src \
                                $(MR)/SRC/Toolkit21.src
	$(HOME)/bin/install_bin 21 1


    $(BKIT)/BLIB/Toolkit24.bin : $(HDRFILES) \
                                $(MR)/SRC/CreSLIB.src \
                                $(MR)/SRC/Toolkit24.src
	$(HOME)/bin/install_bin 24 1


    $(BKIT)/BLIB/Toolkit30.bin : $(HDRFILES) \
                                $(MR)/SRC/Upgrade2.0To3.0.src \
                                $(MR)/SRC/Toolkit30.src
	$(HOME)/bin/install_bin 30 1

    $(BKIT)/BLIB/Toolkit31.bin : $(HDRFILES) \
                                $(MR)/SRC/LoadUnloadProofMethod.src \
                                $(MR)/SRC/CreatePmdTemplate.src \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/SetOfRules_core \
                                $(MR)/SRC/SetOfRules_PASP \
                                $(MR)/SRC/SetOfRules_NonPASP \
                                $(MR)/SRC/MakeSetOfRules_FwdTheories.src \
                                $(MR)/SRC/MakeSetOfRules_IP.src \
                                $(MR)/SRC/PrettyPrint.src \
                                $(MR)/SRC/QueryUser.src \
                                $(MR)/SRC/InterProver.src \
                                $(MR)/SRC/Toolkit31.src
	$(HOME)/bin/install_bin 31 1


    $(BKIT)/BLIB/Toolkit32.bin : $(HDRFILES) \
                                $(MR)/SRC/CreHtml.src \
                                $(MR)/SRC/Introduce.src \
                                $(MR)/SRC/Toolkit32.src
	$(HOME)/bin/install_bin 32 1


    $(BKIT)/BLIB/Toolkit35.bin : $(HDRFILES) \
                                $(MR)/SRC/TranslatorsPASP.src \
                                $(MR)/SRC/TransPASP.src \
                                $(MR)/SRC/LinkPASP.src \
                                $(MR)/SRC/Toolkit35.src
	$(HOME)/bin/install_bin 35 1


    $(BKIT)/BLIB/Toolkit36.bin : $(HDRFILES) \
                                $(MR)/SRC/TransVHDL.src \
                                $(MR)/SRC/Toolkit36.src
	$(HOME)/bin/install_bin 36 1


    $(BKIT)/BLIB/Toolkit37.bin : $(HDRFILES) \
                                $(MR)/SRC/CreHtml.src \
                                $(MR)/SRC/EnumVHDL.src \
                                $(MR)/SRC/Toolkit37.src
	$(HOME)/bin/install_bin 37 1


    $(BKIT)/BLIB/Toolkit38.bin : $(HDRFILES) \
                                $(MR)/SRC/CreVHDLSLIB.src \
                                $(MR)/SRC/Toolkit38.src
	$(HOME)/bin/install_bin 38 1


    $(BKIT)/BLIB/Toolkit39.bin : $(HDRFILES) \
                                $(MR)/SRC/PrettyPrint.src \
                                $(MR)/SRC/CreatePmdTemplate.src \
                                $(MR)/SRC/Standardize_PASP.src \
                                $(MR)/SRC/Standardize_NonPASP.src \
                                $(MR)/SRC/CommonTheory.src \
                                $(MR)/SRC/SetOfRules_core \
                                $(MR)/SRC/LoadUnloadProofMethod.src \
                                $(MR)/SRC/BToolProver.src \
                                $(MR)/SRC/SwitchBTP.src \
                                $(MR)/SRC/Toolkit39.src
	$(HOME)/bin/install_bin 39 1
